server:
  port:8080

spring:
  application:
    name: minitas
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5433/minitas
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop



